class people::wfarr {
  include projects::amen
  include projects::atom
  include projects::bounty
  include projects::boxen
  include projects::bricklayer
  include projects::central
  include projects::ci
  include projects::community
  include projects::destinations
  include projects::dns
  include projects::enterprise-crypto
  include projects::enterprise-manage
  include projects::enterprise-toolchain
  include projects::enterprise-web
  include projects::fi-quote
  include projects::gauges
  include projects::gist
  include projects::git
  include projects::github
  include projects::gitrpc
  include projects::gitscm-next
  include projects::gollum
  include projects::graphme
  include projects::halp
  include projects::haystack
  include projects::heaven
  include projects::help
  include projects::hire
  include projects::hq-puppet
  include projects::hubot-classic
  include projects::infrastructure_wiki
  include projects::initrd
  include projects::janky
  include projects::jobs
  include projects::kod
  include projects::miramar
  include projects::monitors
  include projects::most-wanted
  include projects::network
  include projects::numbers
  include projects::octostatus
  include projects::pages-jekyll
  include projects::pixelhub
  include projects::pollex
  include projects::primer
  include projects::puppet
  include projects::rails
  include projects::setup-puppet
  include projects::setup-web
  include projects::shell
  include projects::slumlord
  include projects::speakeasy
  include projects::speakerdeck
  include projects::swordfish
  include projects::team
  include projects::training
  include projects::vpn
}
